CREATE DATABASE causdb;

CREATE TABLE users(
    id INT NOT NULL AUTO_INCREMENT ,
    userid VARCHAR( 50 ) NOT NULL ,
    PASSWORD VARCHAR( 40 ) NOT NULL ,
    email VARCHAR( 100 ) NOT NULL ,
    creationtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    PRIMARY KEY ( id )
);